extraLabels: {}
  # app.kubernetes.io/env: staging
  # app.kubernetes.io/owner: devops

deployment:
  image: "argoprojlabs/argocd-notifications"
  tag: "v1.0.2"

slack:
  token:
  appUserName:
  channelName:
  appIconUrl: "https://cncf-branding.netlify.app/img/projects/argo/icon/color/argo-icon-color.png"
  messageBody:
    appEnv:
    argocdUrl: