{{- define "common-libs.ingress" -}}
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "common-libs.name" . -}}
{{- $servicePort := .Values.service.port -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
  {{- with .Values.extraLabels }}
     {{ toYaml . | nindent 4}}
  {{- end }}
  {{- include "common-libs.labels" . | nindent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ $fullName }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: 
        pathType: {{ .Values.ingress.pathType | default "ImplementationSpecific"}} 
        backend:
          service:
          {{- if eq .Values.strategy.type "blueGreen" }}
            name: {{ $fullName }}-stable
            port: 
              number: {{ $servicePort }}
          {{- end }}    
          {{- if eq .Values.strategy.type "canary" }}
            name: {{ $fullName }}-stable
            port: 
              name: use-annotation
          {{- end }}
          {{- if eq .Values.strategy.type "rolling-update" }}
            name: {{ $fullName }}-stable
            port: 
              number: {{ $servicePort }}
          {{- end }}           
{{- end }}
{{- end }}