{{- define "common-libs.service" -}}
{{- if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common-libs.name" . }}-stable    
  labels:
    {{- with .Values.extraLabels }}
      {{ toYaml . | nindent 4}}
    {{- end }}
    {{- include "common-libs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
   {{- if eq .Values.service.type "ClusterIP" }}
    - protocol: {{ .Values.service.protocol | default "TCP"}}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport | default .Values.container.portExposed }}
   {{- end }}   
   {{- if eq .Values.service.type "NodePort" }}
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport | default .Values.container.portExposed }}
      nodePort: {{ .Values.service.nodePort }}
   {{- end }}   
  selector:
    {{- include "common-libs.labels" . | nindent 4 }}


{{- if or (eq .Values.strategy.type "blueGreen") (eq .Values.strategy.type "canary") }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common-libs.name" . }}-preview 
  labels:
    {{- with .Values.extraLabels }}
      {{ toYaml . | nindent 4}}
    {{- end }}
    {{- include "common-libs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
   {{- if eq .Values.service.type "ClusterIP" }}
    - protocol: {{ .Values.service.protocol | default "TCP"}}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport | default .Values.container.portExposed }}
   {{- end }}   
   {{- if eq .Values.service.type "NodePort" }}
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport | default .Values.container.portExposed }}
      nodePort: {{ .Values.service.nodePort }}
   {{- end }}   
  selector:
    {{- include "common-libs.labels" . | nindent 4 }}
  {{- end }}   
{{- end }}  
{{- end }}     