# Default values for alpha.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Lib chart ::
nameSpace: argocd

extraLabels:
  app.kubernetes.io/env: uat
  app.kubernetes.io/owner: devops

# Github private repo which should be added during bootstrap.(https)
gitUrl: ## https://github.com/xsxsxs/csdcs-csdcd.git
  
# Repo name for argocd.  
repoName: # myrepo

secret:
  #Github username (Plain text)
  username: #suyog1pathak
  #Api key as password. (Plain text)
  password: #github API Key.

imageTag: v2.0.5  # Argocd Image Tag
  
ingress: {}
## Please find below key values for AWS ALB ingress as annotations
  # enabled: false
  # annotations:
  #   kubernetes.io/ingress.class: alb
  #   alb.ingress.kubernetes.io/load-balancer-name: "my-load-balancer"
  #   alb.ingress.kubernetes.io/group.name: "my-load-balancer-group"
  #   alb.ingress.kubernetes.io/group.order: '1'
  #   alb.ingress.kubernetes.io/inbound-cidrs: 1.1.1.1/32, 2.2.2.2/32
  #   alb.ingress.kubernetes.io/scheme: internet-facing
  #   alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
  #   alb.ingress.kubernetes.io/ssl-redirect: '443'
  #   alb.ingress.kubernetes.io/tags: env=test,Name=my-load-balancer,app=argocd
  #   alb.ingress.kubernetes.io/target-type: ip
  #   alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:xxxxxxxxxxxxxxxx
  #   alb.ingress.kubernetes.io/backend-protocol: HTTP
  #   alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=90
  #   alb.ingress.kubernetes.io/healthcheck-path: /healthz?full=true
  #   alb.ingress.kubernetes.io/healthcheck-interval-seconds: '10'
  #   alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '7'
  #   alb.ingress.kubernetes.io/healthy-threshold-count: '2'
  #   alb.ingress.kubernetes.io/unhealthy-threshold-count: '5'
  # hostname: "argocd.pinaka.com"    
  # serviceName: argocd-server
  # port: 80